# Generated by Django 6.0.5 on 2026-05-12 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='is_buy_bonus',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddIndex(
        #     model_name='gamelog',
        #     index=models.Index(fields=['user', '-created_at'], name='api_gamelog_user_id_01dcdb_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='gamelog',
        #     index=models.Index(fields=['win_amount'], name='api_gamelog_win_amo_27c5e6_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='userwallet',
        #     index=models.Index(fields=['user'], name='api_userwal_user_id_d5bb6b_idx'),
        # ),
    ]
