# Generated by Django 6.0.5 on 2026-05-18 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamelog_is_buy_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(help_text='e.g. bg_music, spin_start, win_epic, scatter_land', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_audio', models.FileField(blank=True, help_text='Upload custom audio file (.mp3 / .wav)', null=True, upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_id', models.CharField(help_text='e.g. crown, red_gem, scatter, mult_500', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol_type', models.CharField(choices=[('regular', 'Regular Symbol'), ('scatter', 'Scatter Symbol'), ('multiplier', 'Multiplier Symbol')], default='regular', max_length=20)),
                ('weight_base', models.FloatField(default=10.0, help_text='Weight/frequency during normal spins')),
                ('weight_free', models.FloatField(default=10.0, help_text='Weight/frequency during free spins')),
                ('multiplier_value', models.FloatField(default=0.0, help_text='Used only if symbol is Multiplier type')),
                ('payout_8_9', models.FloatField(default=0.0, help_text='Payout multiplier for 8-9 matching symbols (or 4 scatters)')),
                ('payout_10_11', models.FloatField(default=0.0, help_text='Payout multiplier for 10-11 matching symbols (or 5 scatters)')),
                ('payout_12_plus', models.FloatField(default=0.0, help_text='Payout multiplier for 12+ matching symbols (or 6 scatters)')),
                ('custom_image', models.ImageField(blank=True, help_text='Upload custom image to replace default asset', null=True, upload_to='symbols/')),
            ],
        ),
    ]
