# Generated by Django 6.0.5 on 2026-05-19 12:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameaudio_symbol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='current_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='free_spin_bet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='free_spins_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='gamelog',
            index=models.Index(fields=['user', '-created_at'], name='api_gamelog_user_id_01dcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='gamelog',
            index=models.Index(fields=['win_amount'], name='api_gamelog_win_amo_27c5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallet',
            index=models.Index(fields=['user'], name='api_userwal_user_id_d5bb6b_idx'),
        ),
    ]
