# Generated by Django 6.0.5 on 2026-05-19 12:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userwallet_current_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressiveJackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_pool', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20)),
                ('minor_pool', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=20)),
                ('major_pool', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=20)),
                ('grand_pool', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
